import mongoose from 'mongoose';

const wordpressIntegrationSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  siteUrl: {
    type: String,
    required: true,
    trim: true
  },
  username: {
    type: String,
    required: true,
    trim: true
  },
  applicationPassword: {
    type: String,
    required: true
  },
  isActive: {
    type: Boolean,
    default: true
  },
  isDefault: {
    type: Boolean,
    default: false
  },
  lastTestedAt: {
    type: Date,
    default: null
  },
  lastTestResult: {
    success: Boolean,
    message: String,
    testedAt: Date
  },
  settings: {
    defaultStatus: {
      type: String,
      enum: ['draft', 'publish', 'private'],
      default: 'draft'
    },
    defaultCategories: [{
      type: Number // WordPress category IDs
    }],
    defaultTags: [{
      type: String
    }],
    autoPublish: {
      type: Boolean,
      default: false
    },
    syncStatus: {
      type: Boolean,
      default: true
    },
    includeBacklink: {
      type: Boolean,
      default: true
    },
    backlinkText: {
      type: String,
      default: 'Generated by SUBSTATE'
    }
  },
  stats: {
    totalPosts: {
      type: Number,
      default: 0
    },
    successfulPosts: {
      type: Number,
      default: 0
    },
    failedPosts: {
      type: Number,
      default: 0
    },
    lastPostAt: {
      type: Date,
      default: null
    }
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, { 
  timestamps: true 
});

// Indexes
wordpressIntegrationSchema.index({ userId: 1 });
wordpressIntegrationSchema.index({ userId: 1, isDefault: 1 });
wordpressIntegrationSchema.index({ userId: 1, isActive: 1 });

// Ensure only one default integration per user
wordpressIntegrationSchema.pre('save', async function() {
  if (this.isDefault && this.isModified('isDefault')) {
    // Remove default flag from other integrations for this user
    await this.constructor.updateMany(
      { 
        userId: this.userId, 
        _id: { $ne: this._id } 
      },
      { isDefault: false }
    );
  }
});

// Methods
wordpressIntegrationSchema.methods.updateStats = function(success) {
  this.stats.totalPosts += 1;
  if (success) {
    this.stats.successfulPosts += 1;
  } else {
    this.stats.failedPosts += 1;
  }
  this.stats.lastPostAt = new Date();
  return this.save();
};

wordpressIntegrationSchema.methods.updateTestResult = function(result) {
  this.lastTestResult = {
    success: result.success,
    message: result.message,
    testedAt: new Date()
  };
  this.lastTestedAt = new Date();
  return this.save();
};

wordpressIntegrationSchema.methods.getConfig = function() {
  return {
    siteUrl: this.siteUrl,
    username: this.username,
    applicationPassword: this.applicationPassword
  };
};

const WordPressIntegration = mongoose.model('WordPressIntegration', wordpressIntegrationSchema);

export default WordPressIntegration;